trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_BUILDKIT: 1
  # Define different tags for main and develop branches
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    imageTag: '$(Build.BuildId)'  # Unique tag for production
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    imageTag: 'dev'  # Static tag for development

steps:
- task: Docker@2
  displayName: 'Login to Azure Container Registry'
  inputs:
    containerRegistry: 'my-service-connection'
    command: 'login'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'my-service-connection'
    repository: 'myfeaturescontainerregistry/acr-repository-3'
    command: 'build'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    arguments: '--build-arg BUILD_ENV=$(BUILD_ENV) --build-arg DOTNET_ENV=$(DOTNET_ENV)'
    tags: |
      $(imageTag)

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'my-service-connection'
    repository: 'myfeaturescontainerregistry/acr-repository-3'
    command: 'push'
    tags: |
      $(imageTag)